# Generated by Django 4.0 on 2022-01-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=160000)),
                ('otp', models.CharField(max_length=4)),
                ('user_level', models.IntegerField(default=2)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.user')),
            ],
        ),
    ]
